### PR TITLE
Add rumble support + enhanced navigation + minor changes 

### PR DESCRIPTION
**Pull request by OneLiberty**
This should add rumble support and improve menu navigation across the app. 

Taking care of #4 

Changes : 
- **MAJOR** : Added rumble support
- **MAJOR** : Improved app navigation
- fix mouse support for 2021 and more tvs
- Deleted some uneeded files
- Few minor changes 
- Changes done by ndriqimlahu
- updated readme. 
- Updated name for the widget (from MoonlightWasm to Moonlight) 
- TV volume UI when changing volume 

I only tested (on my S95B) rumble with a Xbox One Controller, the game Risk of Rain 2 and https://hardwaretester.com/gamepad
Worked fine, i mostly reused what was already done for moonlight-chrome but adapted it to work for the wasm app. 

More test should be done before "release", especially with other tvs and controllers. 

### **Edit : Tested controllers** 

- **Xbox One controller** : Working
- **Xbox 360 controller** : working (thanks @jdin)
- **Xbox Elite Series 2 controller** : working (thanks @Reshaos)  
- **Dualsense** : Working _(dualshock 4 are probably fine too)_ 
- **Stadia controller** : Not working
- **Switch Pro Controller** : Not working _(Couldn't even get it working with the app at all)_ 

_Looking for feedback about navigation in the app_

You can try by yourself using this to install : `docker run -it --rm ghcr.io/oneliberty/moonlight-chrome-tizen:samsung_wasm`

### CODE REVIEW

**Comment by jdin** [comment]
I have tried to build your fork branch to test it but had problems. First of all the name of the final widget was not `MoonlightWasm.wgt` but `Moonlight,wdt`. And then when I have installed to test it, I do see the new icon, but it hangs on startup. Tried multiple times, always the same problem.

**Comment by OneLiberty** [comment]
I should have mentioned the name change, sorry about that. It's actually unnecessary, i might change it back. 
It's weird for the startup bug, i don't have any issue on my side, i'll be looking later. 
Do you have access to logs or anything ? Could you send your tv model number ? 
Thanks !

**Comment by jdin** [comment]
> I should have mentioned the name change, sorry about that

No problem! Just do not forget to update the Dockerfile. This line: 
```Dockerfile
RUN mv build/widget/MoonlightWasm.wgt .
```

> Do you have access to logs or anything ?

I am not an expert in Tizen :) . Is there an easy way to get the logs from TV?

> Could you send your tv model number ?

QN92AA 65 TV  -  QE65QN92AATXXN

Could be that something went wrong during the build. Although I did it on Apple silicon M1 and Windows 11.  The same result for both. Is there maybe an option to share the Docker instance with the built widget or the widget itself?

**Comment by OneLiberty** [comment]
> I am not an expert in Tizen :) . Is there an easy way to get the logs from TV?

Aha, no problem, i'm not a dev at all, this is all new for me, looking back at the implementation of rumble, it looks like something that a dev could have done in 20minutes, it just took me a whole day.. 

Well, i don't have an easy way to show log, i know a way for sure using tizen studio. 
I was able to get log on my Mac (not m1 tho). 

The way I did it was by creating an empty tizen tv project (should default to tizen 7.0 but this is not an issue). 
Deleting every thing that tizen studio adds by default and then copying the content from the widget folder (obtained by entering the files form the docker container) into the empty project. 

_Alternatively you can get the Moonlight.wgt from the docker container and extract it, it contains the same things as widget folder plus certificate files._ 

Then just build the wgt (you might have to create a certificate to build the app) , connect to the TV using the device manager and upload the app using `debug as `--> `1 Tizen Web Application`

This will open chrome devtool, and you'll get access to the console logs. 

This takes a while, but that's how I did it. 
I'm sure there is a better way of doing this, but i'm clearly don't have the knowledge. 

Edit : I've just re-build and reinstalled the app, and it's working fine. 
When starting the app ip might freeze (progress bar not moving) for a minute or two because it's generating a certificate (don't know why) and it can take some times, couldn't it be your issue @jdin ?

**Comment by jdin** [comment]
No the progress bar keeps moving. I usually wait for quite some time. If I install the “official”widget from the docker container without rumble then it works without any problem. At the beginning I though that it is the problem with M1 processor. But then I have tried just normal desktop pc , and still the same problem. I am building always using Dockerfile for now as it is the easiest:). I will try to play with it a bit more to figure out where is the problem.

**Comment by OneLiberty** [comment]
@jdin I might have found the issue. I'll try using an emulator to fix it
I'll edit this post if i managed to fix it 

Edit : pushed fix, please try it and tell me if it works

**Comment by jdin** [comment]
@OneLiberty,  I can confirm that the last commit indeed helped. :) I have now vibration on my xbox 360 controllers. I will test a bit more with the different games. But so far everything is good. Great job!

**Comment by OneLiberty** [comment]
Great ! 
I'm glad it worked ! If everything seems ok for you, I'll push the PR 

I'd like more info from other people, but regarding the size of community it will be hard to enough comment on it. 

Thanks a lot for helping me in this @jdin !

**Comment by Reshaos** [comment]
I have been watching this PR and decided to test your changes too. I cloned your forked repository and manually built the image which took about an hour. Anyways, it worked beautifully on my Q65 TV using the Xbox Elite Series 2 wireless controller.

Great work!

Up to you if you want to fix it, but the dialog boxes are terrible. It didn't correctly deselect the previous option. For example, the exit dialog you added (thank you btw), if you move left and right on the ok or cancel you can't tell what is selected any more, also you don't even have to press A or enter.. if you keep pressing left then it'll assume you confirmed. The dialog boxes are a mess in this app.

**Comment by OneLiberty** [comment]
Glad it worked for you too ! 

Yup navigating is horrible, i'll try to improve that in the following weeks, but for now it works "good enough". 

No need to fork it or anything to try it just do a good ol' `docker run -it --rm ghcr.io/oneliberty/moonlight-chrome-tizen:samsung_wasm` and install as usual

**Comment by henryfa2** [comment]
Hey there o/
I tested it too and can confirm it worked on a SAMSUNG QE55Q83B TV + XBOX One Controller.

**Comment by OneLiberty** [comment]
I've just pushed an update. 
Should take care of @Reshaos concern for the navigation in the app. 
This might fix #6 _feedback needed_

This PR is starting to be a bit messy, i might close it in the next few days (to re-open one after)

**Comment by Reshaos** [comment]
@OneLiberty Awesome! I will give it a try this week. It is best practice to keep PR's small. Looking at the list of fixes/updates this could've been three or four PR's. I'm not the system architect for this project though :).

I very much appreciate the work though!

Update: The navigation is 100% better. Great work!

**Comment by adambenovic** [comment]
Tried your build and I must say, brilliant work!
I do backend webdev for living and probably wouldn't have figured all this out so fast :)
Anyway:
- the GUI looks and feels better
- BT mouse is supported(though BT keyboard won't type anything in)
- Dualshock 4 did rumble once when connected, hopefully will work in games, too
- unfortunately the keyboard issue from #6 is still present 

Building from source now so I am able to hardcode my PC's IP. The first source build takes a long time mainly because of the slow Tizen studio web-cli download from the main download loc: https://download.tizen.org/sdk/Installer/tizen-studio_5.0/web-cli_Tizen_Studio_5.0_ubuntu-64.bin
Replacing that with the USA mirror makes it faster(even tho I'm not in USA) https://usa.sdk-dl.tizen.org/web-cli_Tizen_Studio_5.0_usa_ubuntu-64.bin - might be another suggestion to add to the PR while you are at it :)
Also might be helpful to use newer SDK version? Dunno if it is a good idea, would require experimentation. (v5.5 available)

Tested on UE55CU7172UXXH.

**Comment by OneLiberty** [comment]
Thanks for the feedback @adambenovic 

- I can't speak for Bluetooth keyboard right now, but I'm using a small keyboard mouse combo with a dongle and it works great (S95B on tizen 6.5) 
- Same goes for the IME, maybe those two issues are related. I was able to replicate the issue on tizen 7 emulator, but didn't find anything useful while debugging. I'll look a bit more into next week

- We could update to 5.5, this won't be an issue I think. 
Download speed differs a lot, but for the end user I doesn't change a lot (except for those on tizen 7 that must hardcode their IP).

- Another way we could tackle this is by fixing the host discovery functionality. No clue how unfortunately. 

I might look at it, but honestly I've already put a lot of time into this, I'm not sure I can continue like this for long ! 
I really want this application to be fixed, and I hope we will. 

EDIT : @adambenovic I've just pushed, what i think is the worst workaround for #6 (for some reason, when changin field it increment the last one by one...) 
Also this removes any possibility for something else than an IpV4 to be put, which is pretty bad ...
Could you try it and tell me if it's as bad as it sounds ?

**Comment by OneLiberty** [comment]
I'm closing this, way to many changes for a PR

**Pull request closed without merging**
